theme: jekyll-theme-minimal
title: Darwin Files
description: List of Models
lsi: false
safe: true
source: darwinhanchinli.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
