title: Darwin Li's Files
description: List of Models
theme: jekyll-theme-minimal
show_downloads: true
lsi: false
safe: true
source: darwinhanchinli.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
